version: "3"
services:
  php:
    image: kiksaus/kikdev
    restart: always
    ports:
        - "${SITE_PORT}:443"
    volumes:
        - ../../../../public_html/:/var/www/html:cached
        - ../../../../:/var/www:cached
        - ../../:/var/www/vendor/kiksaus:cached
        - ~/.docker-kikdev/logs:/var/log/apache2/:cached
    networks:
      kikdev:
        aliases:
          - ${SITE_ALIAS}

networks:
  kikdev:
    external:
      name: kikdev