name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      run: |
        git checkout production
        cd assets
        npm install
        npm run bower install
        gulp --production
        cd ..
        git rebase -Xours master
        rm resources/js/.gitignore
        rm resources/css/.gitignore
        git add resources/js
        git add resources/css
        git commit -m "production update"
        git push -f